Vagrant.configure("2") do |config|
  config.vm.box = "generic/ubuntu2204"
  config.vm.box_version = "4.3.12"

  #config.vm.synced_folder "../../../../../..", "/var/script-tut"
  config.vm.provision "shell", 
    path: "../../../../../../scriptbox/generated/ubuntu22_install.sh"
end
