@ECHO OFF
REM Enumerate a fixed set of well-known environment variables, printing
REM  "NAME=value" for each. USERNAME/USERPROFILE/TEMP/COMPUTERNAME are
REM  always set natively by Windows itself, no fallback needed.
REM  USER/HOME/TMPDIR/HOSTNAME are POSIX concepts with no Windows
REM  equivalent - printed only when actually present.
IF DEFINED USER ECHO USER=%USER%
IF DEFINED HOME ECHO HOME=%HOME%
IF DEFINED TMPDIR ECHO TMPDIR=%TMPDIR%
IF DEFINED HOSTNAME ECHO HOSTNAME=%HOSTNAME%
IF DEFINED USERNAME ECHO USERNAME=%USERNAME%
IF DEFINED USERPROFILE ECHO USERPROFILE=%USERPROFILE%
IF DEFINED TEMP ECHO TEMP=%TEMP%
IF DEFINED COMPUTERNAME ECHO COMPUTERNAME=%COMPUTERNAME%
