# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "puppetlabs/ubuntu-12.04-64-puppet"
  config.vm.hostname = "precisebox"

  # Vagrant CFEngine Provisioner
  config.vm.provision :cfengine do |cf|
    cf.am_policy_hub = true
  end
end
