# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "puppetlabs/debian-7.8-64-puppet" # Get Debian Wheezy From Somewhere
  config.vm.hostname = "wheezybox"                  # Give System a Hostname

  config.vm.synced_folder "../../provisioning/salt", "/srv/salt/"

  # Provision System
  config.vm.provision :salt do |salt|
    salt.run_highstate = true
    salt.minion_config = "../../provisioning/minion"
    salt.bootstrap_options = "-F -c /tmp"          # Vagrant Issue #6029
    salt.verbose = true
  end
end
