# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box      = "chef/centos-6.6" # Get Debian Wheezy From Somewhere
  config.vm.hostname = "centos6box"      # Give System a Hostname

  # Vagrant CFEngine Provisioner
  config.vm.provision :cfengine do |cf|
    cf.am_policy_hub = true
  end
end
