VAGRANTFILE_API_VERSION = "2"
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "chef_solo/centos-6.6"

  config.vm.hostname = "centos6box"

  config.vm.provision :ansible do |ansible|
    ansible.playbook = "../../provisioning/playbook.yml"
    ansible.inventory_path = "../../provisioning/inventory"
    ansible.sudo = true
  end

end
