---
packages:
  Debian:
    - dash
    - bash
    - ksh
    - tcsh
    - gawk
    - perl
    - python
    - php5-cli
    - ruby
    - tcl8.5
  RedHat:
    - dash
    - bash
    - ksh
    - tcsh
    - gawk
    - perl
    - python
    - php-cli
    - ruby
    - tcl
