VAGRANTFILE_API_VERSION = "2"
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "http://puppet-vagrant-boxes.puppetlabs.com/ubuntu-server-12042-x64-vbox4210.box"
  config.vm.hostname = "scriptbox"
  config.vm.provision "puppet" do |puppet|
    puppet.manifests_path = "../../manifests/"
    puppet.manifest_file  = "site.pp"
    puppet.module_path = ["../../modules/"]
    puppet.options = "--verbose --debug"
  end
end
