VAGRANTFILE_API_VERSION = "2"
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  # Source File:
  #  https://atlas.hashicorp.com/puppetlabs/boxes/centos-6.6-32-puppet/versions/1.0.1/providers/virtualbox.box
  #  Copied to $HOME/boxen directory
  config.vm.box = "~/boxen/centos-6.6-i386-virtualbox-puppet-1.0.1.box"
  config.vm.hostname = "centos6box"
  config.vm.provision "puppet" do |puppet|
    puppet.manifests_path = "../../manifests/"
    puppet.manifest_file  = "site.pp"
    puppet.module_path = ["../../modules/"]
    puppet.options = "--verbose --debug"
  end
end
