Vagrant.require_version ">= 1.6.2"
VAGRANTFILE_API_VERSION = "2"
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "http://aka.ms/vagrant-win7-ie11"
  config.vm.hostname = "scriptbox"
  config.vm.communicator = "winrm"
  config.vm.network "forwarded_port", guest: 3389, host: 3389

  # Vagrant cannot detect Windows OS, set explicitly
  config.vm.guest = :windows

  config.vm.provider "virtualbox" do |vb|
    vb.customize ["modifyvm", :id, "--memory", "2048"]
    vb.customize ["modifyvm", :id, "--cpus", "2"]
  end

  config.vm.provision "puppet" do |puppet|
    puppet.manifests_path = "../../manifests/"
    puppet.manifest_file  = "site.pp"
    puppet.module_path = ["../../modules/"]
    puppet.options = "--verbose --debug"
  end
end
