# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "puppetlabs/ubuntu-12.04-64-puppet" # Get Ubuntu Precise
  config.vm.hostname = "precisebox"                   # Give System a Hostname

  # Vagrant CFEngine Provisioner
  config.vm.provision :cfengine do |cf|
    cf.am_policy_hub = true
    cf.mode = :bootstrap
    cf.run_file = "../../bundlesofjoy/scriptbox.cf"
  end
end
