# Manifest
# * Site Manifest (site.pp) with node default
# * Host specifie nodes organized per-platform type, e.g. ubuntu22.pp
manifest = manifests/site.pp:manifests/nodes/*.pp

# Module Path
# * ../shared_modules - classifier-agnostic modules, shared by all classifier trees
# * ../.forge-vendor - modules downloaded from the Puppet Forge
modulepath = ../shared_modules:../.forge-vendor
