schema_version: 1
name: dotnet-sdk-10-noble
kind: base
version: '10.0'
variant: noble
status: experimental

provides:
  - dotnet-sdk 10
  - dotnet-runtime 10

compatibility:
  lineage: ubuntu
  release: '24.04'
  architectures: [amd64, arm64]

upstream:
  repository: https://github.com/dotnet/dotnet-docker
  commit: null
  path: README.sdk.md
  image: mcr.microsoft.com/dotnet/sdk:10.0-noble
  digest: sha256:e1ffd2a92ae84c1291bc1b6887501f8af98e6331e7af6d4c8d37168c5e87a64c

license:
  expression: MIT
  notice: null

fragment:
  path: null
  sha256: null

verification:
  - dotnet --info

reviewed: '2026-08-29'
