"""
A live roster module - unlike ../../roster/roster.yaml (a plain file,
regenerated by hand and read as-is), this one is Python code Salt
itself calls fresh on every single salt-ssh invocation. targets() is
the one function any roster module has to provide, whatever it
actually does to produce its answer - here, that means shelling out to
scriptbox/scripts/generate_salt.rb --tree roster (the exact same
generator ../../roster/'s own pre-generated file comes from) to a
throwaway temp file, reading that back, and handing the result
straight to Salt - so every value this run needs (connection info,
every "lessons" step) gets computed on the spot, never stored anywhere
between runs.

__opts__/__utils__ below aren't undefined names - Salt's own loader
injects them into every roster module it loads from roster_dirs (see
../master's own roster_dirs setting), the same way __opts__ appears in
any other Salt extension module.
"""

import subprocess
import tempfile
import os

import yaml

REPO_ROOT = "/var/script-tut"
GENERATE_SALT_RB = REPO_ROOT + "/scriptbox/scripts/generate_salt.rb"
CONFIG_YML = REPO_ROOT + "/scriptbox/config/ubuntu2204.yml"


def targets(tgt, tgt_type="glob", **kwargs):
    """
    Return the targets from a fresh generate_salt.rb --tree roster run,
    computed now, not read back from anything written earlier.
    """
    fd, tmp_path = tempfile.mkstemp(suffix=".yaml")
    os.close(fd)
    try:
        subprocess.run(
            ["ruby", GENERATE_SALT_RB, CONFIG_YML, tmp_path, "--tree", "roster"],
            check=True,
            capture_output=True,
        )
        with open(tmp_path) as f:
            raw = yaml.safe_load(f)
    finally:
        os.unlink(tmp_path)

    return __utils__["roster_matcher.targets"](raw, tgt, tgt_type, "ipv4")
