# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "puppetlabs/debian-7.8-64-puppet"
  config.vm.hostname = "wheezybox"
  config.vm.provision :ansible do |ansible|
    ansible.playbook = "../../provisioning/playbook.yml"
  #  ansible.inventory_path = "../../provisioning/inventory.ini"
    ansible.sudo = true
  end
end
