#!/usr/bin/env ruby
require 'yaml'

# node_classifier.rb - the ENC classifier's node_terminus script (see
#  puppet.conf's own node_terminus = exec / external_nodes = <this
#  file's path>). Puppet calls this once per catalog compile with the
#  requesting node's certname as ARGV[0] and expects a classes:/
#  parameters: YAML document on stdout - see puppet.com/docs/puppet/
#  latest/nodes_external.html.
#
# Two pieces merged at request time, same split as ../hiera/'s own
#  common.yaml (hand-written) vs data/lessons/ubuntu22.yaml (generated):
#  - data/common.yaml - hand-written knobs (lessons::user, the four
#    area gates) - never touched by scriptbox/scripts/generate_puppet.rb.
#  - data/<platform>.yaml - GENERATED by generate_puppet.rb --classifier
#    enc (platform/common_steps/each area's own steps).
#  Kept as two files, not one, so re-running the generator can never
#  clobber a hand-written override - exactly the same reason the hiera
#  classifier keeps common.yaml and lessons/ubuntu22.yaml separate.
#
# PLATFORM_FOR_CERTNAME - only ubuntu22 has a generated data/ entry
#  today, same single-platform scope the Chef cookbook and Ansible role
#  this mirrors currently cover (see ../hiera/hiera.yaml's own comment
#  on the same limitation). Any certname not listed here falls back to
#  'ubuntu22' rather than erroring - add a real entry once a second
#  platform exists.
PLATFORM_FOR_CERTNAME = {}.freeze

data_dir = File.join(__dir__, 'data')
certname = ARGV[0] or abort "usage: #{$PROGRAM_NAME} <certname>"
platform = PLATFORM_FOR_CERTNAME.fetch(certname, 'ubuntu22')

common = YAML.load_file(File.join(data_dir, 'common.yaml'))
doc = YAML.load_file(File.join(data_dir, "#{platform}.yaml"))
doc['classes']['lessons'] = common.merge(doc['classes']['lessons'])

puts doc.to_yaml
