require 'chef'
require 'chef/config'
require 'chef/knife'
#current_dir = File.dirname(__FILE__)
Chef::Config.from_file(File.expand_path('../../.chef/knife.rb'))


VAGRANTFILE_API_VERSION = "2"
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "chef/debian-7.8"

  config.vm.hostname = "wheezybox"

  config.vm.provision :chef_zero do |chef|
    chef.cookbooks_path  = ["../../cookbooks", "../../site-cookbooks"]
    chef.roles_path      = "../../roles"
    chef.nodes_path      = "../../nodes"
    chef.data_bags_path  = "../../data_bags"
    chef.verbose_logging = true
  end

  # config.vm.provision :chef_client do |chef|
  #   chef.chef_server_url        = Chef::Config[:chef_server_url]
  #   chef.validation_key_path    = Chef::Config[:validation_key]
  #   chef.validation_client_name = Chef::Config[:validation_client_name]
  #   chef.chef_zero.enabled      = true
  #   chef.node_name              = config.vm.hostname
  #   #chef.node_name = options[:hostname]
  #   #chef.run_list = options[:run_list]
  #   chef.provisioning_path = "/etc/chef"
  #   chef.log_level = :info
  # end

  config.vm.provision :chef_client do |chef|
    chef.chef_server_url        = "http://127.0.0.1:8889"
    chef.validation_key_path    = Chef::Config[:validation_key]
    chef.validation_client_name = Chef::Config[:validation_client_name]
    chef.chef_zero.enabled      = true
    chef.node_name              = config.vm.hostname
    #chef.node_name = options[:hostname]
    #chef.run_list = options[:run_list]
    chef.provisioning_path = "/etc/chef"
    chef.log_level = :info
  end

end
