SCRIPT_TUT_PATH="../../../.."
# ansible_local runs ansible-playbook *inside* the guest, so provision/
#  (site.yml, roles/, vars/) has to actually be synced there first -
#  this Vagrantfile's own default share only covers systems/ubuntu_2204/
#  itself, not its ../.. parent where provision/ actually lives.
ANSIBLE_ROOT="../.."

Vagrant.configure("2") do |config|
  config.vm.box = "generic/ubuntu2204"
  config.vm.box_version = "4.3.12"
  config.vm.hostname = "ansible-node-01.test"
  config.vm.synced_folder "#{SCRIPT_TUT_PATH}", "/var/script-tut"

  # Tighten Security required for use with desired ansible.cfg
  # * PROBLEM: Ansible security guard will ignore `ansible.cfg` when 
  #     it is world writable, 777 (rwxrwxrwx) 
  # * SOLUTION: set mount options with dmode=755, fmode=644
  config.vm.synced_folder "#{ANSIBLE_ROOT}", "/vagrant/ansible", mount_options: ["dmode=755", "fmode=644"]

  config.vm.provision "ansible_local" do |ansible|
    ansible.playbook = "ansible/provision/site.yml"
    ansible.verbose = true

    # Install Roles & Collections
    # * roles: installed from mounted path at /vagrant/ansible/provison/.galazy-vendor/roles
    # * collections: installed using default at $HOME/.ansible/collections/ansible_collections
    # Collecitons Workaround
    # * PROBLEM: 
    #   * mounted vboxsf doesn't support symlinks and [Errno 71] Protocol error
    #   * installing from MSYS2 also causes ENOENT as symlinks are not supported
    # * SOLUTION: install collections using guest's default location 
    ansible.galaxy_role_file  = "ansible/provision/requirements.yml"
    ansible.galaxy_roles_path = "ansible/provision/.galaxy-vendor/roles"
    ansible.galaxy_command    = "ansible-galaxy role install -r %{role_file} -p %{roles_path} --force && " \
                                "ansible-galaxy collection install -r %{role_file} --force"
  end
end

