# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "puppetlabs/ubuntu-12.04-64-puppet" # Get Ubuntu Precise From Somewhere
  config.vm.hostname = "precisebox"                   # Give System a Hostname

  config.vm.synced_folder "../../provisioning/salt", "/srv/salt/"

  # Provision System
  config.vm.provision :salt do |salt|
    salt.run_highstate = true
    salt.minion_config = "../../provisioning/minion"
  #  salt.bootstrap_options = "-F -c /temp -P"
    salt.bootstrap_options = "-F -c /tmp -P"    # Vagrant Issues #6011 & #6029
    salt.verbose = true
  end
end


# PURE -F -c /temp = FAIL IN Ubuntu Precise
