VAGRANTFILE_API_VERSION = "2"
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "chef/debian-7.8"

  config.vm.hostname = "wheezybox"

  config.vm.provision ::chef_solo do |chef|
    chef.cookbooks_path  = ["../../cookbooks", "../../site-cookbooks"]
    chef.roles_path      = "../../roles"
    chef.nodes_path      = "../../nodes"
    chef.data_bags_path  = "../../data_bags"
    chef.verbose_logging = true
    chef.add_recipe "scriptbox"
  end
end
