require 'yaml'
require 'optparse'
require 'fileutils'
require_relative 'resolve_order'
require_relative 'generate_install_script' # for command_for/write_install_script/dialect_for
require_relative 'verify_commands' # for uname_string/match_platform - see system_info's own comment

CONFIG_DIR = File.join(__dir__, '..', 'config')

# deep_merge - combines every config/*.yml into one map. Nested hashes
#  (e.g. a "scripts" block defined in more than one file) merge together
#  key by key; anything else, the later file wins.
def deep_merge(a, b)
  a.merge(b) do |_key, old_val, new_val|
    old_val.is_a?(Hash) && new_val.is_a?(Hash) ? deep_merge(old_val, new_val) : new_val
  end
end

def load_merged_config
  Dir.glob(File.join(CONFIG_DIR, '*.yml')).sort.reduce({}) do |merged, path|
    deep_merge(merged, YAML.load_file(path))
  end
end

if __FILE__ == $PROGRAM_NAME
  options = { select: [], exclude: [], output: nil }
  OptionParser.new do |opts|
    opts.banner = 'usage: gen_installer --platform NAME [--select TAG,TAG] [--exclude TAG,TAG] [--output PATH]'
    opts.on('--platform NAME', 'platform key from config/ to generate an installer for') { |v| options[:platform] = v }
    # See resolve_order.rb's own tag_eligible?/select_by_tags (issue
    #  #16) - a tagged package entry (e.g. rbenv/pyenv/asdf alternatives
    #  for the same language) needs at least one of its own tags named
    #  here, or the literal tag 'default', to be included at all.
    opts.on('--select TAGS', 'comma-separated tags to opt into') { |v| options[:select] = v.split(',').map(&:strip) }
    opts.on('--exclude TAGS', 'comma-separated tags to veto, overriding --select/default') { |v| options[:exclude] = v.split(',').map(&:strip) }
    opts.on('--output PATH', 'write here instead of generated/<platform>_install.<ext>') { |v| options[:output] = v }
  end.parse!

  platform = options[:platform]
  if platform.nil? || platform.empty?
    warn 'gen_installer: --platform is required'
    exit 1
  end

  tree = load_merged_config

  # 1. finds key, prints a message if not found
  if RESERVED_KEYS.include?(platform) || !tree.key?(platform)
    warn "gen_installer: no such platform: #{platform}"
    exit 1
  end

  # Resolved right after the platform key itself is confirmed valid,
  #  before anything below reads a single field out of it - see
  #  resolve_order.rb's own substitute_variables/RESERVED_KEYS comment
  #  on why this is scoped to tree[platform] alone, not the whole
  #  merged tree (variables: lives nested inside each platform's own
  #  key, not as a top-level shared block visible to every platform).
  tree[platform] = substitute_variables(tree[platform], tree[platform]['variables'] || {})

  # 2. detects this machine's own environment - uname_string/match_platform
  #  (verify_commands.rb) already handle Cygwin/MSYS2/WSL1/Linux distros/
  #  macOS/native Windows correctly (including a native Windows Ruby with
  #  no `uname` on PATH at all, via a PowerShell OS-version probe) -
  #  reused rather than reimplemented here, so this can never drift from
  #  what the real verify_commands.rb report actually detects.
  detected = uname_string

  # 3. checks the detected environment is listed as supported for this platform
  env_entry = (tree['environments'] || []).find { |e| e['platform'] == platform }
  supported = env_entry && Array(env_entry['supports']).include?(detected)
  unless supported
    warn "gen_installer: detected environment '#{detected}' is not supported for platform '#{platform}'"
    exit 1
  end

  # 4. generates the script
  steps = flatten(tree[platform])
  # Snapshotted before resolve! mutates steps' own order - see
  #  write_install_script's own comment on why. Also before select_by_
  #  tags, same reasoning select_sections already relies on elsewhere -
  #  a tag-filtered `steps` may not include every natural-order sibling
  #  relocate_cross_cutting's own prefix walk looks for.
  natural_steps = steps.dup
  steps, omitted = select_by_tags(steps, options[:select], options[:exclude])
  resolve!(steps)
  dedup!(steps)

  generated_dir = File.join(__dir__, '..', 'generated')
  FileUtils.mkdir_p(generated_dir)
  dialect = dialect_for(tree, platform)
  header_lines = [
    "Generated by gen_installer --platform #{platform} - do not edit by hand.",
    "Detected environment: #{detected}"
  ]
  # See resolve_order.rb's own select_by_tags - a step whose own needs:
  #  had no eligible provider at all (not just "wasn't selected this
  #  run") got dropped rather than emitted as a command guaranteed to
  #  fail; surfaced here instead of silently disappearing.
  omitted.each do |step, missing|
    header_lines << "Omitted: [#{step[:path]}] #{step[:type]}: #{step[:name]} - needs '#{missing}', no eligible provider (check --select/--exclude, or the manifest's own default tags)"
  end
  out_path = write_install_script(platform, steps, tree, dialect, generated_dir, header_lines, natural_steps, apt_mirror_for(tree, platform), out_path: options[:output])
  puts "wrote #{out_path}"
end
