require 'yaml'
require 'optparse'
require 'fileutils'
require_relative 'resolve_order'
require_relative 'generate_install_script' # for command_for/write_install_script/dialect_for
require_relative 'verify_commands' # for uname_string/match_platform - see system_info's own comment

CONFIG_DIR = File.join(__dir__, '..', 'config')
RESERVED_KEYS = %w[scripts environments].freeze

# deep_merge - combines every config/*.yml into one map. Nested hashes
#  (e.g. a "scripts" block defined in more than one file) merge together
#  key by key; anything else, the later file wins.
def deep_merge(a, b)
  a.merge(b) do |_key, old_val, new_val|
    old_val.is_a?(Hash) && new_val.is_a?(Hash) ? deep_merge(old_val, new_val) : new_val
  end
end

def load_merged_config
  Dir.glob(File.join(CONFIG_DIR, '*.yml')).sort.reduce({}) do |merged, path|
    deep_merge(merged, YAML.load_file(path))
  end
end

if __FILE__ == $PROGRAM_NAME
  options = {}
  OptionParser.new do |opts|
    opts.banner = 'usage: gen_installer --platform NAME'
    opts.on('--platform NAME', 'platform key from config/ to generate an installer for') { |v| options[:platform] = v }
  end.parse!

  platform = options[:platform]
  if platform.nil? || platform.empty?
    warn 'gen_installer: --platform is required'
    exit 1
  end

  tree = load_merged_config

  # 1. finds key, prints a message if not found
  if RESERVED_KEYS.include?(platform) || !tree.key?(platform)
    warn "gen_installer: no such platform: #{platform}"
    exit 1
  end

  # 2. detects this machine's own environment - uname_string/match_platform
  #  (verify_commands.rb) already handle Cygwin/MSYS2/WSL1/Linux distros/
  #  macOS/native Windows correctly (including a native Windows Ruby with
  #  no `uname` on PATH at all, via a PowerShell OS-version probe) -
  #  reused rather than reimplemented here, so this can never drift from
  #  what the real verify_commands.rb report actually detects.
  detected = uname_string

  # 3. checks the detected environment is listed as supported for this platform
  env_entry = (tree['environments'] || []).find { |e| e['platform'] == platform }
  supported = env_entry && Array(env_entry['supports']).include?(detected)
  unless supported
    warn "gen_installer: detected environment '#{detected}' is not supported for platform '#{platform}'"
    exit 1
  end

  # 4. generates the script
  scripts = tree['scripts'] || {}
  steps = flatten(tree[platform])
  # Snapshotted before resolve! mutates steps' own order - see
  #  write_install_script's own comment on why.
  natural_steps = steps.dup
  resolve!(steps)
  dedup!(steps)

  generated_dir = File.join(__dir__, '..', 'generated')
  FileUtils.mkdir_p(generated_dir)
  dialect = dialect_for(tree, platform)
  out_path = write_install_script(platform, steps, scripts, dialect, generated_dir, [
    "Generated by gen_installer --platform #{platform} - do not edit by hand.",
    "Detected environment: #{detected}"
  ], natural_steps)
  puts "wrote #{out_path}"
end
