#!/usr/bin/env ruby
require 'yaml'
require 'fileutils'
require 'optparse'
require_relative 'resolve_order'
require_relative 'generate_chef_databag' # for step_to_entry/consolidate_apt/root_key/LESSON_AREAS/COMMON_AREA
require_relative 'generate_ansible_vars' # for deep_stringify_keys

# generate_puppet.rb - same source of truth (scriptbox/config/*.yml),
#  same resolved lessons step list as generate_chef_databag.rb and
#  generate_ansible_vars.rb, just serialized for whichever of Puppet's
#  three classifier methods --classifier names (default: hiera - see
#  CLASSIFIERS below). No real deployment supports all three at once;
#  --classifier picks exactly one output shape per invocation, the same
#  way a real Puppet control-repo commits to one classifier and one
#  ../../configbox/puppet/shared_modules/lessons module (classifier-agnostic -
#  see its own init.pp) consumes whichever shape this produced:
#
#  - hiera (recommended default - see ../../configbox/puppet/README.md):
#    hieradata/lessons/<platform>.yaml, keyed lessons::<class>::<param>
#    for Puppet's own automatic class-parameter lookup. Data/code stay
#    separate - the module never even knows hiera is involved.
#  - enc: a classes:/parameters: YAML document, the shape an External
#    Node Classifier's node_terminus prints on stdout for one node -
#    same data, pushed instead of pulled.
#  - site: a literal node '<platform>' { class { 'lessons': ... } }
#    manifest with the full step data inlined as Puppet DSL - the
#    oldest, least idiomatic of the three (code and data mixed in one
#    generated .pp file), kept for parity/comparison with Chef's own
#    data-bag-JSON-inlined-by-generation approach.
CLASSIFIERS = %w[site hiera enc].freeze

# pp_string(s) - `s` as a single-quoted Puppet string literal. Single-
#  quoted, not double: Puppet double-quoted strings interpolate `$var`,
#  and every script step's own cmd body is full of literal $HOME/$PATH/
#  etc. that must reach the generated manifest completely unevaluated -
#  double-quoting here would silently turn "cmd: $HOME/.cargo/env" into
#  an attempt to interpolate a Puppet variable named $HOME that doesn't
#  exist. Puppet single-quoted strings only ever recognize two escapes
#  (\\ and \'), so those are the only two characters that need escaping
#  here - everything else (including embedded newlines) passes through
#  literally, which is exactly what a multi-line bash cmd body needs.
def pp_string(s)
  escaped = s.to_s.gsub('\\') { '\\\\' }.gsub("'") { "\\'" }
  "'#{escaped}'"
end

# to_pp(obj, indent) - `obj` (already string-keyed - see deep_
#  stringify_keys below) as Puppet DSL: a Hash becomes a `{ key => value,
#  ... }` literal (Puppet requires `=>`, not JSON's `:` - the one
#  reason this can't just reuse JSON.pretty_generate the way the Chef
#  data bag does), an Array becomes `[ ... ]`, everything else via
#  pp_string/to_s. `indent` is the nesting level of the line the value
#  itself starts on, so a caller's own hand-indented "foo => " prefix
#  and this function's own closing brace/bracket always line up.
def to_pp(obj, indent)
  pad = '  ' * indent
  inner_pad = '  ' * (indent + 1)
  case obj
  when Hash
    return '{}' if obj.empty?
    body = obj.map { |k, v| "#{inner_pad}#{pp_string(k)} => #{to_pp(v, indent + 1)}," }.join("\n")
    "{\n#{body}\n#{pad}}"
  when Array
    return '[]' if obj.empty?
    body = obj.map { |v| "#{inner_pad}#{to_pp(v, indent + 1)}," }.join("\n")
    "[\n#{body}\n#{pad}]"
  when true, false
    obj.to_s
  when nil
    'undef'
  when Numeric
    obj.to_s
  else
    pp_string(obj.to_s)
  end
end

# write_site(name, lessons_data, out_path) - see CLASSIFIERS's own
#  'site' entry. One node block per platform, wholesale-overwritten
#  each run (not merged the way generate_ansible_vars.rb's single
#  shared group_vars file is) - same one-file-per-platform simplicity
#  as the Chef data bag's own data_bags/lessons/<platform>.json.
def write_site(name, lessons_data, out_path)
  lines = []
  lines << "# GENERATED by scriptbox/scripts/generate_puppet.rb --classifier site"
  lines << "#  from #{name}'s own scriptbox/config/*.yml manifest. Do not edit by"
  lines << '#  hand - re-run the generator instead. Data is inlined directly as'
  lines << "#  class{} resource-like declarations (no hiera lookup, no ENC) - the"
  lines << "#  'site manifest' classifier: everything this node needs lives in one"
  lines << '#  literal node block. See ../../shared_modules/lessons/manifests/init.pp for'
  lines << '#  what each parameter means - the class itself is classifier-agnostic.'
  lines << "node #{pp_string(name)} {"
  lines << "  class { 'lessons':"
  lines << "    platform     => #{pp_string(name)},"
  lines << "    common_steps => #{to_pp(lessons_data[COMMON_AREA], 2)},"
  # Every area below is declared explicitly, right here, with its own
  #  real $steps - so the parent class must not also auto-`contain` it
  #  (that's what its area-gate params are for). Skipping this leaves
  #  lessons::init.pp's own `if $gen_scripts { contain lessons::gen_
  #  scripts }` (default true) to declare the class first with no
  #  steps, and the explicit declaration below then collides with it as
  #  a duplicate declaration.
  LESSON_AREAS.each { |area| lines << "    #{area} => false," }
  lines << '  }'
  LESSON_AREAS.each do |area|
    lines << ''
    lines << "  class { 'lessons::#{area}':"
    lines << "    steps => #{to_pp(lessons_data[area], 2)},"
    lines << '  }'
  end
  lines << '}'

  FileUtils.mkdir_p(File.dirname(out_path))
  # mode: 'wb' - on a native-Windows Ruby (RUBY_PLATFORM x64-mingw-ucrt,
  #  the default on this repo's Windows dev box), text-mode File.write
  #  silently translates every \n to \r\n. That's invisible for the .pp
  #  syntax itself, but multi-line step 'cmd' bodies get embedded \r\n
  #  along with it - and \r right before a keyword like `fi`/`then`
  #  isn't the same token to bash, so the *generated script* breaks even
  #  though the *manifest* parses fine. Binary mode keeps \n literal
  #  regardless of host OS.
  File.write(out_path, "#{lines.join("\n")}\n", mode: 'wb')
end

# write_hiera(name, lessons_data, out_path) - see CLASSIFIERS's own
#  'hiera' entry. lessons::<class>::<param> keys, exactly the automatic-
#  parameter-lookup names Puppet's own hiera backend binds a class
#  parameter to without any explicit lookup() call in the class body -
#  the Puppet analogue of Ansible's group_vars auto-load, not Chef's
#  explicit data_bag_item(key) call (that's the 'enc'/'site' shapes).
def write_hiera(name, lessons_data, out_path)
  data = {
    'lessons::platform' => name,
    'lessons::common_steps' => lessons_data[COMMON_AREA],
  }
  LESSON_AREAS.each { |area| data["lessons::#{area}::steps"] = lessons_data[area] }

  FileUtils.mkdir_p(File.dirname(out_path))
  File.write(out_path, "---\n#{data.to_yaml.sub(/\A---\n/, '')}", mode: 'wb')
end

# write_enc(name, lessons_data, out_path) - see CLASSIFIERS's own 'enc'
#  entry. classes:/parameters: - the exact document shape a Puppet
#  External Node Classifier's node_terminus is expected to print on
#  stdout for one node (see puppet.com/docs/puppet/latest/nodes_
#  external.html). A real node_terminus script would map a certname to
#  a platform and then just cat this file - see ../../configbox/puppet/
#  enc/README.md.
def write_enc(name, lessons_data, out_path)
  classes = {
    'lessons' => {
      'platform' => name,
      'common_steps' => lessons_data[COMMON_AREA],
    },
  }
  LESSON_AREAS.each { |area| classes["lessons::#{area}"] = { 'steps' => lessons_data[area] } }
  doc = { 'classes' => classes, 'parameters' => { 'lessons_platform' => name } }

  FileUtils.mkdir_p(File.dirname(out_path))
  File.write(out_path, "---\n#{doc.to_yaml.sub(/\A---\n/, '')}", mode: 'wb')
end

# parse_puppet_args(argv) - <config.yml> <out_path> [--classifier
#  site|hiera|enc] [--select TAG,TAG] [--exclude TAG,TAG]. --select/
#  --exclude match generate_databag_args's own semantics exactly (see
#  its own comment) - only --classifier is new here.
def parse_puppet_args(argv)
  options = { select: [], exclude: [], classifier: 'hiera' }
  OptionParser.new do |opts|
    opts.on('--select TAGS') { |v| options[:select] = v.split(',').map(&:strip) }
    opts.on('--exclude TAGS') { |v| options[:exclude] = v.split(',').map(&:strip) }
    opts.on('--classifier CLASSIFIER') { |v| options[:classifier] = v }
  end.parse!(argv)
  [argv[0], argv[1], options]
end

if __FILE__ == $PROGRAM_NAME
  config_path, out_path, options = parse_puppet_args(ARGV)
  if config_path.nil? || config_path.empty? || out_path.nil? || out_path.empty?
    warn "usage: #{$PROGRAM_NAME} <config.yml> <out_path> [--classifier site|hiera|enc] [--select TAG,TAG] [--exclude TAG,TAG]"
    exit 1
  end
  unless CLASSIFIERS.include?(options[:classifier])
    warn "#{$PROGRAM_NAME}: --classifier must be one of #{CLASSIFIERS.join('/')}, got '#{options[:classifier]}'"
    exit 1
  end

  tree = YAML.load_file(config_path)
  name = root_key(tree)
  tree = substitute_variables(tree, tree[name]['variables'] || {})

  all_steps = flatten(tree[name])
  all_steps, omitted = resolve_included(all_steps, options[:select], options[:exclude])
  warn_omissions(omitted)
  topological_order(all_steps)
  version_omitted = check_version_needs!(all_steps)
  version_omitted.each { |s| warn "#{$PROGRAM_NAME}: #{s[:omitted_reason]}" }

  lessons_steps = all_steps.select { |s| (['lessons'] + LESSON_AREAS).include?(owning_function(s)) }
  lessons_steps = pull_in_cross_area_deps(lessons_steps, all_steps)
  lessons_steps = lessons_steps.reject { |s| %w[system omitted_version_need].include?(s[:type]) }
  dedup!(lessons_steps)

  lessons_data = {}
  lessons_data[COMMON_AREA] = consolidate_apt(lessons_steps.reject { |s| LESSON_AREAS.include?(owning_function(s)) }.map { |s| step_to_entry(s, tree) })
  LESSON_AREAS.each do |area|
    entries = lessons_steps.select { |s| owning_function(s) == area }.map { |s| step_to_entry(s, tree) }
    lessons_data[area] = consolidate_apt(entries)
  end
  # String keys throughout (Hash and Array alike, at every depth) - see
  #  generate_ansible_vars.rb's own deep_stringify_keys comment. Applied
  #  once here rather than per-writer so all three writers (to_pp
  #  included) see the same plain string-keyed shape.
  lessons_data = deep_stringify_keys(lessons_data)

  case options[:classifier]
  when 'site'  then write_site(name, lessons_data, out_path)
  when 'hiera' then write_hiera(name, lessons_data, out_path)
  when 'enc'   then write_enc(name, lessons_data, out_path)
  end

  puts "wrote #{out_path} (--classifier #{options[:classifier]})"
end
