#!/usr/bin/env ruby
require 'fileutils'
require 'optparse'
require 'tempfile'
require 'yaml'
require_relative 'generate_install_script'
require_relative 'verify_commands'

# A Justfile is an execution backend, not a second resolver. Generate the
# ordinary, fully-resolved installer first, then place that exact program in a
# single script recipe. Keeping the plan in one interpreter process is
# important: invoking `just` from a terminal does not make each recipe shell
# interactive, and separate recipes would lose exports/functions established
# by earlier installation steps.

def just_platform_supported?(config_path, platform, detected)
  env_path = File.join(File.dirname(config_path), 'env.yml')
  return nil unless File.file?(env_path)

  environments = YAML.load_file(env_path)['environments'] || []
  entry = environments.find { |candidate| candidate['platform'].to_s.casecmp?(platform) }
  entry && Array(entry['supports']).include?(detected)
end

def indent_just_recipe(body)
  body.lines.map { |line| line.strip.empty? ? "\n" : "    #{line}" }.join
end

def write_resolved_justfile(config_path, out_path, select_tags: [], exclude_tags: [],
                            selectors: [], check_host: true)
  tree = YAML.load_file(config_path)
  platform = root_key(tree)
  raise "no platform manifest found in #{config_path}" unless platform

  detected = uname_string
  supported = just_platform_supported?(config_path, platform, detected)
  if check_host && supported == false
    raise "detected environment '#{detected}' is not supported for platform '#{platform}' " \
          "(use --allow-host-mismatch only when intentionally cross-generating)"
  end

  tree = substitute_variables(tree, tree[platform]['variables'] || {})
  natural_steps = flatten(tree[platform])
  steps, omitted = resolve_included(
    natural_steps.dup, select_tags, exclude_tags,
    selectors: expand_selectors(selectors)
  )
  topological_order(steps)
  dedup!(steps)

  header_lines = [
    "Generated by generate_justfile.rb from #{File.basename(config_path)} - do not edit by hand.",
    "Resolved platform: #{platform}",
    "Detected generation environment: #{detected}"
  ]
  omitted.each do |step, missing|
    header_lines << "Omitted: [#{step[:path]}] #{step[:type]}: #{step[:name]} - " \
                    "needs '#{missing}', no eligible provider"
  end
  check_version_needs!(steps).each { |step| header_lines << "Omitted: #{step[:omitted_reason]}" }

  dialect = dialect_for(tree, platform)
  Tempfile.create(["#{platform}_resolved", dialect == 'powershell' ? '.ps1' : '.sh']) do |installer|
    installer.close
    write_install_script(
      platform, steps, tree, dialect, File.dirname(installer.path), header_lines,
      natural_steps, apt_mirror_for(tree, platform), out_path: installer.path
    )
    program = File.binread(installer.path).sub(/\A#![^\n]*\n/, '')
    if dialect == 'powershell'
      # just writes a script recipe to a temporary file. Keep the parent
      # invocation alive until the elevated child finishes, or just may remove
      # that temporary file before the child has opened $PSCommandPath.
      program = program.sub('Start-Process powershell.exe -Verb RunAs -ArgumentList ',
                            'Start-Process powershell.exe -Verb RunAs -Wait -ArgumentList ')
    end

    FileUtils.mkdir_p(File.dirname(File.expand_path(out_path)))
    File.open(out_path, 'wb') do |file|
      file.puts '# Generated file. Change the platform manifest or generator instead.'
      file.puts "# Source: #{File.basename(config_path)}"
      file.puts "# Platform: #{platform}; generated on: #{detected}"
      file.puts
      if dialect == 'powershell'
        file.puts '[script("powershell.exe", "-NoProfile", "-ExecutionPolicy", "Bypass", "-File")]'
      else
        file.puts '[script("bash")]'
      end
      file.puts '# Install the fully resolved provisioning plan.'
      file.puts 'install:'
      file.write(indent_just_recipe(program))
    end
  end

  out_path
end

if __FILE__ == $PROGRAM_NAME
  options = { select: [], exclude: [], selectors: [], check_host: true }
  parser = OptionParser.new do |opts|
    opts.banner = 'usage: generate_justfile.rb <config.yml> [SECTION ...] --output PATH [options]'
    opts.on('--select TAGS', 'comma-separated provider tags to enable') do |value|
      options[:select] = value.split(',').map(&:strip)
    end
    opts.on('--exclude TAGS', 'comma-separated tags to veto') do |value|
      options[:exclude] = value.split(',').map(&:strip)
    end
    opts.on('--output PATH', 'resolved Justfile path (required)') { |value| options[:output] = value }
    opts.on('--allow-host-mismatch', 'permit intentional cross-generation') { options[:check_host] = false }
  end
  parser.parse!

  config_path = ARGV.shift
  options[:selectors] = ARGV
  if config_path.nil? || options[:output].nil?
    warn parser
    exit 1
  end

  begin
    path = write_resolved_justfile(
      config_path, options[:output], select_tags: options[:select],
      exclude_tags: options[:exclude], selectors: options[:selectors],
      check_host: options[:check_host]
    )
    puts "wrote #{path}"
  rescue StandardError => error
    warn "generate_justfile.rb: #{error.message}"
    exit 1
  end
end
