Vagrant.configure("2") do |config|
  config.vm.box = "gusztavvargadr/windows-11"
  config.vm.box_version = "2607.1.0"

  config.vm.synced_folder "../../../../../..",
    "C:/script-tut"
  config.vm.provision "shell",
    path: "../../../../../../scriptbox/generated/windows_install.ps1"
end
