SCRIPT_TUT_PATH="../../../../../.."

Vagrant.configure("2") do |config|
  config.vm.box = "gusztavvargadr/windows-11"
  config.vm.box_version = "2607.1.0"

  config.vm.synced_folder "#{SCRIPT_TUT_PATH}",
    "C:/script-tut"

  config.vm.provision "shell",
    path: "#{SCRIPT_TUT_PATH}/scriptbox/generated/windows_install.ps1",
    privileged: true

  config.vm.provision "shell", inline: <<-'SHELL'
    set MSYSTEM=UCRT64
    "C:\tools\msys64\usr\bin\bash.exe" -lc "/c/script-tut/scriptbox/generated/msys2_install.sh"
  SHELL

  config.vm.provision "shell", inline: <<-'SHELL'
    "C:\tools\cygwin\bin\bash.exe" -lc "/cygdrive/c/script-tut/scriptbox/generated/cygwin_install.sh"
  SHELL
end
