---

- hosts: all
  gather_facts: yes

  vars_files:
    - vars/main.yml

  tasks:
  - name: install the Debian packages
    apt: name={{ item }} state=latest
    with_items:
          - dash
          - bash
          - ksh
          - tcsh
          - gawk
          - perl
          - python
          - php5-cli
          - ruby
          - tcl8.5
    when: ansible_os_family == "Debian"

  - name: install the RedHat packages
    yum: pkg={{ item }} state=latest
    with_items:
          - dash
          - bash
          - ksh
          - tcsh
          - gawk
          - perl
          - python
          - php-cli
          - ruby
          - tcl
    when: ansible_os_family == "RedHat"
