---

- hosts: all
  gather_facts: yes

  vars_files:
     - vars/main.yml

  tasks:
    - name: install the Debian packages
      apt: name={{ item }} state=latest
      with_items: "{{ packages }}"
      when: ansible_os_family == "Debian"

    - name: install the RedHat packages
      yum: pkg={{ item }} state=latest
      with_items: "{{ packages }}"
      when: ansible_os_family == "RedHat"

    #  - name: Debugging
    #    debug: msg="{{packages}}"
