---

- hosts: all
  gather_facts: yes

  vars_files:
     - vars/main.yml

  tasks:
    - include: "tasks/Debian.yml"
      when: ansible_os_family == "Debian"

    - include: "tasks/RedHat.yml"
      when: ansible_os_family == "RedHat"
